### ISSUE TITLE
How do i merge GH2DX force pad as guitar with base GH2 PS2 ISO?

### ISSUE THREAD

**Issue by JamesIsWack** [hmxmilohax/Guitar-Hero-II-Deluxe-360#14]
I've looked everywere and cant find answers. I just want to play GH2 for god sake Why is there NOTHING in the readme about this?????

**Comment by jnackmclain** [comment]
Because 3.0 is not ready for ps2. If you took the time to look at the [readme](https://github.com/hmxmilohax/Guitar-Hero-II-Deluxe-360#features)

![image](https://user-images.githubusercontent.com/55568980/213504396-5d3fbc91-78ae-4f7a-a5e2-8f4c186373e1.png)

[action builds](https://github.com/hmxmilohax/Guitar-Hero-II-Deluxe/actions)

![image](https://user-images.githubusercontent.com/55568980/213504711-89925ce3-4747-42dc-a63d-8f2f30c9c7a1.png)

or the [nightly link](https://nightly.link/hmxmilohax/Guitar-Hero-II-Deluxe/workflows/build/2.0)

![image](https://user-images.githubusercontent.com/55568980/213504813-cec85d21-9f62-4489-b92d-7188f9bbeea1.png)

to the actual [PS2 Repo](https://github.com/hmxmilohax/Guitar-Hero-II-Deluxe)
![image](https://user-images.githubusercontent.com/55568980/213504945-4f358fa2-1716-407c-8b54-0bb6371568c8.png)

you'd find it. Don't come into github issues hot like this, it makes it very unappealing to provide you support.
